debug: false

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: uberamd/hugo
    tags: 
      - v0.18.1
      - latest
    file: v0.18/Dockerfile
    insecure: false
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: uberamd/hugo
    tags: 
      - v0.17
    file: v0.17/Dockerfile
    insecure: false
