debug: false

pipeline:
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: uberamd/hugo
    context: v0.18
    tags: 
      - latest
      - v0.18.1
    dockerfile: Dockerfile
    insecure: false
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: uberamd/hugo
    context: v0.17
    tags: 
      - v0.17
    dockerfile: Dockerfile
    insecure: false
